/*
 * DO NOT EDIT - generated by declawer - DO NOT EDIT
 */
package com.example.andreas.recycler;

import android.os.Handler;

import ca.odell.glazedlists.EventList;
import ca.odell.glazedlists.impl.gui.ThreadProxyEventList;

/**
 * Proxies events from all threads to the Swing event dispatch thread. This allows
 * any thread to write a source {@link ca.odell.glazedlists.EventList} that will be updated on the
 * Swing thread.
 *
 * @author <a href="mailto:jesse@swank.ca">Jesse Wilson</a>
 */
public class AndroidThreadProxyEventList extends ThreadProxyEventList {
    
    private Handler handler;

	/**
     * Create a {@link AndroidThreadProxyEventList} that mirrors the specified source
     * {@link ca.odell.glazedlists.EventList} for access on the Swing thread.
     */
    public AndroidThreadProxyEventList(EventList source) {
        super(source);
        handler = new Handler();
    }
    
    /**
     * Schedule the specified runnable to be run on the proxied thread.
     */
    protected void schedule(Runnable runnable) {    	
    	handler.post(runnable);
    }
}
